"""Initial migration: students, diary_entries, marks

Revision ID: 3ff9c17a53ea
Revises: 08e781556b0e
Create Date: 2025-12-01 23:14:07.009069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff9c17a53ea'
down_revision: Union[str, None] = '08e781556b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
