"""remove marks table

Revision ID: 6266df8ef09f
Revises: 9522b757206e
Create Date: 2025-12-02 00:27:36.931077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6266df8ef09f'
down_revision: Union[str, None] = '9522b757206e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mark', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_mark', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('share_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='marks_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='marks_pkey'),
    sa.UniqueConstraint('share_key', name='marks_share_key_key')
    )
    # ### end Alembic commands ###
