"""remove section and roll_no

Revision ID: 9522b757206e
Revises: 08e781556b0e
Create Date: 2025-12-02 00:07:38.358806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9522b757206e'
down_revision: Union[str, None] = '08e781556b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'section')
    op.drop_column('students', 'roll_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('roll_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('section', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
